<?php

/**
 * @file
 * Install, update and uninstall functions for the Search API Exclude module.
 */

/**
 * Implements hook_schema().
 */
function search_api_exclude_schema() {
  $schema['search_api_exclude'] = array(
    'description' => 'Stores the nodes which are excluded from indexing.',
    'fields' => array(
      'nid' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
    ),
    'primary key' => array('nid'),
  );
  return $schema;
}

/**
 * Implements hook_install().
 */
function search_api_exclude_install() {
  // Set default config
  $config = config('search_api_exclude.settings');
  $config->set('types', array());
  $config->save();
}

/**
 * Implements hook_uninstall().
 */
function search_api_exclude_uninstall() {
  config_clear('search_api_exclude.settings', 'types');
}

/**
 * Adapts the {search_api_exclude} table to only store excluded nodes.
 */
function search_api_exclude_update_7101() {
  db_delete('search_api_exclude')
    ->condition('node_exclude', 0)
    ->execute();
  db_drop_index('search_api_exclude', 'node_exclude');
  db_drop_field('search_api_exclude', 'node_exclude');
  $spec = array(
    'type' => 'int',
    'unsigned' => TRUE,
    'not null' => TRUE,
  );
  db_change_field('search_api_exclude', 'nid', 'nid', $spec);

  t('The update has been successfully executed. Please re-index content on all affected Search API indexes for the node exclusion to take effect.');
}

/**
 * Move search_api_exclude settings from variables to config.
 */
function search_api_exclude_update_1000() {
  $config = config('search_api_exclude.settings');
  $config->set('types', update_variable_get('search_api_exclude_types', array()));
  $config->save();

  update_variable_del('search_api_exclude_types');
}
