<?php
/**
 * @file
 * Common function for the module, just extending serach_api
 */

/**
 * Implements hook_search_api_query_alter().
 */
function search_api_node_exclude_search_api_query_alter($query) {  
  $exclude_nids = array(214,340564);

  $filter = $query->createFilter('AND');
  foreach ($exclude_nids as $nid) {
    $filter->condition('nid', $nid, '<>');
  }
  $query->filter($filter);
}

/**
 * Implements hook_permission().
 */
function search_api_node_exclude_permission() {
  return array(
    'administer search api node exclude' => array(
      'title' => t('administer search api node exclude'),
      'description' => t('Administer Search api node exclude'),
    ),
  );
}

/**
 * Implements hook_form_alter().
 * @todo this functions sucks.
 */
function search_api_node_exclude_form_alter(&$form, $form_state, $form_id) {
  if (!empty($form['#node_edit_form'])) {
    if (user_access('administer search api node exclude') && variable_get('search_api_node_exclude_setting_' . $form['type']['#value'], 0)) {
      $node = $form['#node'];
      $form['search_api_node_exclude'] = array(
        '#type' => 'fieldset',
        '#title' => t('Search engine settings'),
        '#collapsible' => TRUE,
        '#collapsed' => TRUE,
        '#access' => user_access('administer node_noindex'),
        '#weight' => 20,
        '#group' => 'additional_settings',
      );
      $form['search_api_node_exclude']['setting'] = array(
        '#type' => 'checkbox',
        '#title' => t('Exclude from searchengines'),
        '#description' => t('If enabled a "noindex"-header will be set on this node. This should mean that this node will not be indexed and not occur in search engine results'),
        '#default_value' => isset($node->noindex) ? $node->noindex : variable_get('search_api_node_exclude_setting_' . $form['type']['#value'], 0),
        '#weight' => 5,
      );
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function search_api_node_exclude_form_node_type_form_alter(&$form, $form_state) {
  $form['search_api_node_exclude'] = array(
    '#type' => 'fieldset',
    '#title' => t('Search api node exclude'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#group' => 'additional_settings',
  );
  $form['search_api_node_exclude']['search_api_node_exclude_setting'] = array(
    '#type' => 'checkbox',
    '#title' => t('Could be excluded from search api search.'),
    '#default_value' => variable_get('search_api_node_exclude_setting_' . $form['#node_type']->type, 0),
    '#description' => t('Could this node type be excluded in Search api?'),
  );
}